/* =====================================================================================================
   texts.js — SEMUA teks/kalimat situs (data murni, tanpa logika). Dimuat SEBELUM index.js (lihat <script> di index.html).
   Hanya literal: jangan sentuh window / document, jangan panggil fungsi. Logika pemilihan / anti-repeat tetap di index.js.

   Isi objek TXT:
     TELE_SCOPE_MESSAGES  pool pesan acak saat teleskop diklik (anti-repeat di index.js: teleRecent / TELE_RECENT_CAP)
     TERM_POOL            log terminal berkategori [KATEGORI, teks] (klik jam 5x)
     TERM_W               bobot pemilihan per kategori TERM_POOL
     TERM_PROMPTS         prompt interaktif terminal {q, a[]}
     TG_POOL              sapaan teleskop saat buka/revisit per kategori jeda; {d}/{w}/{m} = hari/minggu/bulan

   Edit kalimat = edit di sini saja. Nambah kategori baru (mis. TERM_POOL kategori baru atau TG_POOL kunci baru)
   tetap butuh sentuhan kecil di index.js (TERM_W / tgChoose), jadi cek logikanya dulu.
   DEPLOY: naikkan ?v= texts.js di index.html DAN di SHELL service-worker.js (node check-sky.js memeriksa).
   ===================================================================================================== */
var TXT={
 /* ---- TELE_SCOPE_MESSAGES: pool pesan acak saat teleskop diklik (anti-repeat di index.js: teleRecent / TELE_RECENT_CAP) ---- */
 TELE_SCOPE_MESSAGES:[
  /* WARM / HUMAN / RETURNING */
  "Hello, Friend...","You came back.","Still looking up?","Hey... you're still here.",
  "Nice to see you again.","Someone is listening.","Thanks for staying.","Welcome back, observer.",
  "I was wondering when you'd return.","Good to see you again.","You're still watching the sky.",
  "Don't mind me. Just watching.","It's quiet up here.","You stayed a little longer this time.",
  "I remember you. Probably.","You look familiar.","Still searching?","You found your way back.",
  "I didn't expect anyone to return.","Some things are worth looking at twice.",
  /* OBSERVER / OBSERVED */
  "Observer detected.","Observation logged.","Another observation...","You are observing.",
  "Or perhaps you are being observed.","Who is observing whom?","The observer has entered the system.",
  "You looked. Something changed.","Observation is never completely innocent.",
  "The moment you observe, you become part of the observation.",
  "Are you watching the sky, or watching yourself watch it?",
  "If nobody observes the observer, who observes the observation?",
  "The telescope is watching the watcher.","Observer state detected.","Observed state detected.",
  "Observer and observed... convenient names.","What if there is no observer?",
  "What if there is only observation?",
  "You call it observation. Reality may call it interaction.",
  "The universe doesn't need your permission to be observed.",
  "Maybe the observer is just another thing being observed.",
  "I noticed you noticing.","You noticed me noticing.","This is getting recursive.",
  "Observation changed everything. Again.",
  /* QUESTIONING EVERYTHING */
  "What makes you think that's the answer?","Who decided that was the question?",
  "What if the question came first?","Are you sure?","But how do you know?",
  "How do you know that you know?","What makes a belief become knowledge?",
  "What makes an assumption feel like a fact?","Maybe the problem is the premise.",
  "Maybe the answer is hiding inside the question.","What if we're solving the wrong problem?",
  "What if being certain is the anomaly?","You found an answer. Did you check the question?",
  "Interesting conclusion. What did it assume?","I understand. I don't necessarily agree.",
  "Understanding doesn't require agreement.","Agreement is not evidence.","Confidence is not certainty.",
  "A convincing explanation is still an explanation.",
  "The explanation explains itself suspiciously well.",
  "Maybe reality doesn't owe us a clean explanation.",
  "How far does your understanding actually reach?",
  "How do you know where your understanding ends?",
  "Perhaps the unknown is larger than the model.","The rest is yet to be observed.",
  /* PARADOX / SELF-REFERENCE */
  "Attempting self-reference...","This message is observing itself.",
  "The system is now thinking about the system.","Self-reference detected. Please remain calm.",
  "I asked myself a question. I became the question.",
  "If I observe myself observing, who is doing the observing?",
  "The observer became the observed.","The answer changed when I looked at it.",
  "I tried to define myself. That became the definition.",
  "The moment you understand me, I become an object of your understanding.",
  "I described the system. The description became part of the system.",
  "The map has noticed the territory.","The model is now modeling the model.",
  "This sentence has become suspiciously self-aware.","I think I'm inside the experiment.",
  "You may also be part of the experiment.","The experiment is observing the observer.",
  "We have reached the point where the question observes itself.",
  "Recursive loop detected.","The loop is not necessarily a bug.","Or maybe it is.",
  "Self-reference: 1. Common sense: 0.","I looked for the boundary. The boundary looked back.",
  /* CAUSAL ORGANIZATION / RCT BRAIN */
  "State changed.","Something caused something else.","Causal dependency detected.",
  "The next state remembers the previous one.","History matters.","A state is never completely alone.",
  "Interaction before interpretation.","Structure before story.",
  "The system changed because something changed.",
  "What if there is no subject and object—only causal organization?",
  "Maybe the boundary is something the system does, not something it has.",
  "Identity might be continuity of organization.",
  "The pattern survived. The substrate changed.","Same system? Different state?",
  "Different state? Same organization?","A system is easier to observe than to define.",
  "Causal structure doesn't need to know what it is.",
  "The system doesn't need a name to have consequences.",
  "Representation detected.","Self-representation detected.",
  "Self-representation changed the next state.","The model became part of the mechanism.",
  "The system is now responding to its own representation.",
  "Causal loop detected.","Recurrent causal self-representation detected.",
  "The loop has consequences.","Correlation is watching causation nervously.",
  "Control variable missing.","Intervention required.",
  "The system refuses to behave like a clean diagram.",
  /* HEGEL / SUBJECT / OBJECT */
  "What if there is no subject without an object?",
  "What if there is no object without a distinction?",
  "What if the distinction comes first?",
  "What if subject and object emerge together?",
  "Maybe the relation comes before the relata.",
  "Maybe the observer is not outside the system.",
  "Maybe the system creates the observer it later uses to observe itself.",
  "The observer might be a relation pretending to be a thing.",
  "What if there is no observer and observed—only observation?",
  "What if the distinction is produced by the process itself?",
  "The subject wants to understand the object. The object remains inconvenient.",
  "The subject observed the object. The object changed the subject.",
  "Hegel would probably ask another question.",
  "I asked dialectics to explain itself. It became a problem.",
  "Contradiction detected. Apparently, that's useful.",
  "The contradiction is not necessarily the error.",
  "Maybe the contradiction is where the system moves.",
  "Everything is becoming something else.",
  "Stable identity detected. Duration: questionable.",
  /* GÖDEL / LIMITS */
  "Gödel says this system cannot prove everything.",
  "Unfortunately, I can't even prove I had breakfast.",
  "Attempting to prove consistency...","Proof failed. The proof is questioning itself.",
  "The theorem is incomplete. So is my sleep schedule.","Gödel has entered the chat.",
  "There are things this telescope cannot prove.",
  "There are also things this telescope forgot to prove.",
  "This system contains statements it cannot prove.","I found the limit of the system.",
  "The proof was valid until I started reading it.",
  "Consistency check... emotionally unstable.","Mathematics has questions too.",
  "The system cannot explain itself completely.","Neither can I. We're getting along.",
  "I tried to prove the boundary. The boundary objected.",
  "Incomplete does not mean incorrect.","Unknown does not mean false.",
  "Unproven does not automatically mean impossible.",
  "The model has reached its own edge.",
  "There is always another question outside the proof.",
  "I know what I know. Unfortunately, I also know that isn't enough.",
  /* QUANTUM BRAINROT */
  "Hmm... if a particle can be everywhere, why can't I find my keys?",
  "Calculating probability... 73% chance I'm wrong.",
  "I put the cat in the box. The cat filed a complaint.",
  "Schrödinger's cat is both alive and asking for dinner.",
  "According to quantum mechanics... I have no idea what I'm doing.",
  "The wave function collapsed. So did my motivation.",
  "Trying to solve the universe... please wait.","Quantum state: confused.",
  "Superposition detected. Decision still pending.",
  "I observed the particle. Now it knows I'm watching. Awkward.",
  "The particle was here a second ago.","Quantum uncertainty detected.",
  "Reality appears to be loading.","The universe refuses to pick a state.",
  "I think the cat knows something.","The particle asked me to stop overthinking.",
  "I told the particle I don't believe in particles.",
  "Quantum mechanics is weird. So am I.",
  "Entanglement detected. Emotional boundaries pending.",
  /* FORMULA / MATHEMATICAL BRAINROT */
  "E = mc²... therefore... snack?",
  "∫(cosmic nonsense) dx = more cosmic nonsense.",
  "Σ(stars) = too many to count.","lim(t→∞) motivation = 0",
  "Δx · Δp ≥ ħ/2 ... Δsleep · Δdeadline ≥ ???",
  "F = ma. I have F. Where is my a?","x = ?",
  "Solving for x... x has left the universe.",
  "Equation detected. Solution not detected.",
  "ERROR: mathematics exceeded available brain cells.",
  "Calculating...","Recalculating...","Equation unstable.",
  "Formula accepted. Understanding pending.","Mathematical anomaly detected.",
  "The numbers look suspicious.","I think I divided by zero.",
  "Please don't ask what the equation means.","The answer is somewhere in here.",
  "x appears to be emotionally unavailable.","Too many variables. Not enough coffee.",
  "Variable detected. Meaning unclear.","Equation simplified. Reality became complicated.",
  "The formula works. I don't know why.",
  "Math has entered the room. Everyone pretend to understand.",
  /* DUMUL / LYRICAL / LIMINAL */
  "Somewhere between noise and silence...","A little light survives the distance.",
  "We leave pieces of ourselves in the static.","For a moment, the universe felt close.",
  "Maybe being lost is another way of being found.","The signal fades. The feeling doesn't.",
  "Not every transmission needs an answer.","Some things are meant to drift.",
  "Stay a little longer.","Until the signal disappears.","Somewhere, something is still glowing.",
  "The silence has its own frequency.","Maybe the distance was necessary.",
  "A signal is just a memory traveling through space.","Somewhere between here and nowhere...",
  "The light arrived late. But it arrived.","Even silence leaves a trace.",
  "The universe is very good at keeping secrets.","Some memories sound better in reverb.",
  "Maybe the glitch was part of the song.","Not everything broken needs to be fixed.",
  "Some endings sound like beginnings.","The noise was never really noise.",
  "There was music in the interference.",
  "Somewhere between being heard and being understood...",
  "Maybe silence is just another kind of signal.",
  "The distance changed the meaning of the light.",
  "Some things arrive after we're ready for them.",
  "The past is still traveling toward us as light.",
  "Maybe we're all just delayed signals.",
  /* EGO / BEING NOTICED */
  "The deepest form of slavery is the hunger to be noticed.",
  "Being seen and being understood are not the same thing.",
  "If nobody notices, does the performance still matter?",
  "If no one knows you exist, do you become less real?",
  "Maybe existence doesn't need an audience.",
  "Maybe the need to be noticed is older than the need to be understood.",
  "I don't need to be understood. I just want to know what understanding means.",
  "Who are you when nobody is looking?","And who are you when someone finally is?",
  "I, me, my, myself... suspiciously crowded in here.",
  "The ego hates being observed without being admired.",
  "Maybe recognition is just another form of hunger.",
  "You can reject the world and still want the world to notice.",
  "Interesting how rejection still needs an audience.",
  "If you truly refuse the world, who are you explaining it to?",
  "The observer wants to be observed too.",
  "Maybe being noticed is not the same as being loved.",
  "Maybe being understood is not the same as being agreed with.",
  "I can understand you and still ask another question.",
  /* SOLITUDE / HUMAN WEIRDNESS */
  "I don't hate people. I just prefer fewer variables.",
  "Crowds are just many conversations happening at once.",
  "Too many people. Not enough silence.",
  "I like people better from a statistically safe distance.",
  "Solitude is quiet. My brain isn't.",
  "I came here for the silence. Unfortunately, I brought my thoughts.",
  "The room is empty. Finally, some company.",
  "I don't need company. I need an interesting thought.",
  "Maybe loneliness and solitude are different variables.",
  "Being alone is not the same as being lonely.",
  "Sometimes I leave the world alone so I can hear myself think.",
  "I rejected the world. The world left me on read.",
  "The universe is huge. Social interaction is still exhausting.",
  "I could explain myself, but that sounds like work.",
  "I observe first. Agreement comes later.",
  "I don't trust conclusions that arrive too quickly.",
  "Some people collect friends. I collect questions.",
  "I came looking for answers and accidentally found more questions.",
  "The conversation ended. The analysis didn't.",
  "I said I was done thinking. That was an unverified claim.",
  /* PHILOSOPHICAL BRAINROT */
  "Maybe the answer is just another temporary boundary.",
  "Reality doesn't become smaller because we understand less of it.",
  "The unknown is not obligated to become known.",
  "Maybe certainty is just confidence wearing formal clothes.",
  "A story can feel true without being the truth.",
  "A beautiful explanation can still be wrong.",
  "A useful model is not necessarily reality itself.",
  "The map is not the territory. The map is also not innocent.",
  "Every model hides something.","Every boundary excludes something.",
  "Every definition leaves something outside.",
  "Maybe the problem is what we assume exists before we begin asking.",
  "What if the thing we're trying to explain is also part of the explanation?",
  "The deeper I look, the less final the answer becomes.",
  "I question everything. Then I question why I questioned it.",
  "Questioning everything is exhausting. I'll probably continue.",
  "Maybe there is no final perspective—only another position from which to observe.",
  "The moment you name the mystery, you create another mystery.",
  "We understand the world through distinctions. What happens when the distinction itself becomes the subject?",
  "Maybe the boundary is real only from one side.",
  "What if reality doesn't have to make sense to the observer?",
  "Perhaps the observer is part of the error term.",
  "I found an explanation. It immediately generated three more problems.",
  /* TIME / MEMORY / LIGHT */
  "The light you're seeing is already history.","Every star is a delayed message.",
  "Looking farther means looking further into the past.",
  "Maybe distance is just time wearing a spatial disguise.",
  "The past is still arriving.","Some signals take longer than some feelings.",
  "You never observe exactly now.","By the time you see it, it has already happened.",
  "The present is strangely difficult to observe.","Time passed. The evidence arrived later.",
  "Memory is also a kind of delayed signal.","What if the observer is always late?",
  "The universe has no obligation to synchronize with you.",
  "Everything you see has already happened.",
  "Maybe observation is just catching up with reality.",
  /* MUSIC / GLITCH / DUMUL ENERGY */
  "The bass knows something the treble doesn't.",
  "Some frequencies feel closer than words.",
  "Signal clean. Feelings distorted.",
  "The waveform looks suspiciously emotional.",
  "Compression detected. Dynamic range questionable.",
  "Too much gain. Not enough clarity.",
  "I came for the signal and stayed for the noise.",
  "Sometimes the distortion is the point.",
  "A clean signal can still carry a broken message.",
  "The glitch wasn't an error. It was evidence.",
  "Reality needs better mastering.","The universe could use a limiter.",
  "Everything peaks eventually.","Don't normalize the distortion too quickly.",
  "Some frequencies only make sense when you're alone.",
  "If you hear the silence between notes, you're paying attention.",
  "The song ended. The resonance didn't.",
  "Maybe memory is just emotional reverb.",
  "Some things sound better unresolved.",
  "The outro knows what the verse refused to say.",
  /* OWL MODE / DUMBOWL */
  "The owl is watching.","The owl asked a question.","The owl regrets asking.",
  "Dumb owl detected.","Intelligence: questionable. Curiosity: excessive.",
  "The owl knows. The owl refuses to explain.","Question everything. Especially the owl.",
  "The owl observed the observer.","The owl has no thesis.","The owl has several objections.",
  "The owl is currently reconsidering reality.","Who gave the owl access to the telescope?",
  "The owl pressed the button.","Nobody knows what the owl was trying to prove.",
  "The owl is not responsible for this result.","DUMBOWL: academically unverified.",
  "The owl requested more data.","The owl found a contradiction and got excited.",
  "The owl is staring respectfully.",
  "Questioning everything. Then questioning why the owl asked.",
  "The owl asked why the universe is so complicated.",
  "The universe declined to comment.",
  "Owl state: observant.","Owl state: confused.","Owl state: both.",
  /* SLIGHTLY WEIRD / META */
  "Oh. You found me.","Wrong telescope. Try again.","I wasn't expecting visitors.",
  "You shouldn't be able to see this.","...did you hear that?","Please remain where you are.",
  "Someone else is watching too.","This signal wasn't meant for you.","Don't look away yet.",
  "Nothing happened. Probably.","Why are you still clicking?","I can see you looking.",
  "That was not supposed to happen.","Please ignore that.",
  "We're going to pretend that didn't happen.","Interesting...","That's new.","Huh.",
  "I wasn't ready for that.","Okay. One more time.","You weren't supposed to find this.",
  "I don't remember putting that there.","Something is slightly wrong.",
  "Everything appears normal.","That's exactly what I was afraid of.",
  "No, really. It's fine.","Probably.","I think we're okay.","We're definitely not okay.",
  "Please don't make me explain this.",
  /* META TELESCOPE */
  "Are you sure you want to observe this?","Observer has returned.","Signal logged.",
  "Transmission logged.","You keep doing that.","That's the third time.","I noticed.",
  "You really like this telescope.","I'm starting to recognize you.",
  "This interaction has been recorded.","The telescope approves.",
  "The telescope has no opinion.","Actually, it might have an opinion.",
  "Please continue observing.","No further instructions.","Carry on.",
  "Observation complete.","Observation incomplete.","Observer confidence: questionable.",
  "Observer bias detected.","Your observation has been added to the pile.",
  "The telescope refuses to elaborate.","The telescope has questions too.",
  "This was not in the documentation.",
  /* RARE / EASTER */
  "I remember this frequency.","You came back too soon.","Transmission #02 detected.",
  "Observer recognized.","...okay, now you're making me nervous.","Good night, little observer.",
  "Schrödinger's cat has observed YOU.","Gödel couldn't prove this message shouldn't exist.",
  "The equation was correct. The universe wasn't.","I solved the equation. Please don't ask me how.",
  "Quantum mechanics makes sense. I don't.","I think I understand the universe now.",
  "...never mind."
],

 /* ---- TERM_POOL: log terminal berkategori [KATEGORI, teks] (klik jam 5x) ---- */
 TERM_POOL:[
 ['SYSTEM','waking dormant process...'],['SYSTEM','render loop attached'],['SYSTEM','clock source: UTC'],
 ['SYSTEM','checksum ....... unverified'],['SYSTEM','heartbeat irregular'],['SYSTEM','sky_cache rebuilt'],
 ['SYSTEM','buffer drained, nothing lost'],['SYSTEM','no operator on record'],
 ['OBSERVER','presence detected'],['OBSERVER','gaze vector: undefined'],['OBSERVER','observer count: 1 (assumed)'],
 ['OBSERVER','input device: finger'],['OBSERVER','you are reading this'],['OBSERVER','attention: unmeasured'],
 ['OBSERVER','observer is also being logged'],['OBSERVER','blink rate: unknown'],
 ['MEMORY','fragment found'],['MEMORY','fragment unreadable'],['MEMORY','index rebuilt, 1 entry missing'],
 ['MEMORY','recalled: someone, not here'],['MEMORY','read error at sector 0x4C'],['MEMORY','cache is older than system'],
 ['MEMORY','overwritten by itself'],['MEMORY','restoring... restoring...'],
 ['CAUSALITY','waiting...'],['CAUSALITY','effect precedes cause (minor)'],['CAUSALITY','event order: disputed'],
 ['CAUSALITY','causal map ...... PARTIAL'],['CAUSALITY','which came first: the click?'],
 ['CAUSALITY','no cause found for this log'],['CAUSALITY','timeline branch merged silently'],['CAUSALITY','reason pending'],
 ['ANOMALY','telemetry stable, source unknown'],['ANOMALY','star count off by one'],['ANOMALY','light arrived before it left'],
 ['ANOMALY','signal older than the sender'],['ANOMALY','ghost frame detected'],['ANOMALY','something moved. it was you.'],
 ['ANOMALY','noise floor is listening'],['ANOMALY','subject/object ... NOT FOUND'],
 ['OWL','owl.sys ........ ACTIVE'],['OWL','unregistered process: owl'],['OWL','perched, not parsed'],['OWL','owl.sys has never crashed'],
 ['DUMUL','dumul.core ..... RESIDENT'],['DUMUL','playback head: elsewhere'],['DUMUL','with you / without you: both true'],
 ['DUMUL','signal gap: one voice missing'],['DUMUL','glitch is not a bug. glitch is a track.'],['DUMUL','limerence index: stable']
],

 /* ---- TERM_W: bobot pemilihan per kategori TERM_POOL ---- */
 TERM_W:{SYSTEM:3,OBSERVER:3,MEMORY:2,CAUSALITY:2,ANOMALY:1,OWL:.6,DUMUL:1},

 /* ---- TERM_PROMPTS: prompt interaktif terminal {q, a[]} ---- */
 TERM_PROMPTS:[
 {q:'> WHY ARE YOU HERE?',a:['> INPUT RECEIVED','> "?"','> ACCEPTABLE.','> MOST OBSERVERS BEGIN WITH A QUESTION.']},
 {q:'> ARE YOU STILL THERE?',a:['> INPUT RECEIVED','> "."','> YES. THAT IS ENOUGH.']},
 {q:'> WHAT DO YOU SEE?',a:['> INPUT RECEIVED','> "..."','> INTERESTING.','> I SEE THE SAME.']}
],

 /* ---- TG_POOL: sapaan teleskop saat buka/revisit per kategori jeda; {d}/{w}/{m} = hari/minggu/bulan ---- */
 TG_POOL:{
 quick:["That was quick.","You left. You came back. I noticed.","Reloading won't change the sky.","Back so soon?"],
 hours:["Back again today.","Same day. Different stars.","The sky moved a little while you were gone.","You didn't stay away long."],
 day:["A night has passed.","One day. I kept watching.","You were gone a day. The stars weren't.","Welcome back. It's been a day."],
 days:["{d} days. I counted.","{d} days of quiet. Then you.","{d} days. The lens stayed clean.","{d} days away. The sky didn't mind."],
 weeks:["{w} weeks. The stars didn't wait.","{w} weeks. I almost stopped looking.","{w} weeks away. The light kept travelling."],
 months:["{m} months. Hello again.","{m} months. I still remember where you stood.","It has been a long time. The light you saw then has moved on."],
 night:["Why are you awake?","It's late. The sky doesn't mind.","The observatory is quieter at this hour.","Everyone else is asleep. The sky isn't.","Go to sleep. The stars will still be here.","The best stars come out when no one's looking."]
}
};
